### ISSUE TITLE
Do we need to worry about Client pooling?

### ISSUE THREAD

**Issue by born2net** [lalitkapoor/node-pg-util#2]
I understand this lib is a wrapper for https://github.com/brianc/node-postgres
but do we need to worry / manage client pooling?

tx for the support
FYI I tested this lib with TypeScript 2.1 async / await and so far so good!

regards

Sean

**Comment by lalitkapoor** [comment]
@born2net it currently uses the default pool values (which looks to be 10 connections). I'd be open to a pull request that allows for pooling options to be taken in.

**Comment by born2net** [comment]
got it tx
